In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [ ]:
import numpy as np

In [ ]:
!pip install numpy

In [ ]:
np.__version__

In [ ]:
a = np.array ([1,2,3,4,5,6,7])
a

In [ ]:
a[:6]

In [ ]:
L[:6]

In [ ]:
a[3:]

In [ ]:
a[-1]

In [ ]:
a[-2]

In [ ]:
a[2:-3]

In [ ]:
a[-5]

In [ ]:
a[-5-1]

In [ ]:
a[-1:2]

In [ ]:
np.size(a)

In [ ]:
a[a[2]]

In [ ]:
L[L[3]]

In [ ]:
L.reverse()
L

In [ ]:
a.sort()
a

In [ ]:
np.shape(a)

In [ ]:
a = a.reshape(1,7)
np.shape(a)

In [ ]:
a

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6, 7])
a

In [ ]:
a[1]

In [ ]:
L[:][0]

In [ ]:
L = [[1,2,3],[4,5,6],[7,8,9]]
L

In [ ]:
L[:][0]

In [ ]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

In [ ]:
a[:,-1] = 5
a

In [ ]:
a.shape

In [ ]:
a.size

In [ ]:
a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
np.size(a,0)

In [ ]:
np.size(a,1)

In [ ]:
np.ndim(a)

In [ ]:
np_mix_matrix = np.array([['one',2],['three',4],['five',6]])
np_mix_matrix

In [ ]:
a = np.array(np_mix_matrix[:,1], dtype=int)
a

In [ ]:
a = np.zeros((2,2))
a

In [ ]:
a = np.ones((10,10))
a

In [ ]:
c = np.full((4,4),8)
c

In [ ]:
d = np.eye(4)
d

In [ ]:
2*np.ones((2,2))

In [ ]:
c*d

In [ ]:
np.sqrt(np.full((2,2),4))

In [ ]:
2*np.ones((2,2)*2)

In [ ]:
np.empty((20,20))

In [ ]:
np.power(a,2)

In [ ]:
np.random.rand()

In [ ]:
np.random.randint(10)

In [ ]:
np.random.seed(1)
np.random.randint(2,5)

In [ ]:
np.round(np.random.rand(6,3))

In [ ]:
[np.random.randint(5) for item in range (10)]

In [ ]:
a = [1,2,3,4,5,6,7,8,9,10]
np.random.choice(a,5,replace=False)

replace=False เพื่อไม่ให้ซ้ำกัน


In [ ]:
np_matrix = np.random.randint(3,size = (5,5))
np_matrix

In [ ]:
i,j = np.where(np_matrix == 2)

In [ ]:
i

In [ ]:
j

In [ ]:
i,j = np.where(np_matrix == 2)
[(i[ii],j[ii]) for ii in range(len(i))]

In [ ]:
row,column = np.where(np_matrix == 2)
[(row[i],column[i]) for i in range(len(column))]

In [ ]:
np.version

In [ ]:
rng = np.random.RandomState(0)
rng.rand()

In [ ]:
rng = np.random.RandomState(0)
np_matrix = np.random.randint(3,size = (5,5))
np_matrix

In [2]:
import numpy as np

# EX. 2

In [13]:
np_matrix = np.random.randint(10,size = (10,5))
np_matrix

array([[7, 2, 3, 2, 1],
       [4, 8, 4, 2, 9],
       [2, 3, 4, 9, 2],
       [5, 0, 3, 4, 3],
       [8, 8, 1, 0, 4],
       [6, 9, 8, 7, 5],
       [0, 3, 6, 8, 6],
       [3, 0, 0, 4, 8],
       [2, 8, 9, 3, 3],
       [7, 0, 7, 6, 5]])

In [22]:
np_matrix = np.random.randint(4,size = (10,5))
np_matrix

array([[3, 2, 3, 3, 3],
       [3, 2, 3, 1, 3],
       [2, 1, 2, 2, 3],
       [0, 2, 2, 0, 3],
       [0, 1, 3, 0, 0],
       [2, 3, 3, 2, 1],
       [3, 2, 1, 1, 3],
       [1, 0, 0, 3, 0],
       [0, 1, 1, 0, 0],
       [2, 2, 1, 0, 3]])

In [23]:
i,j = np.where(np_matrix == 2)
[(i[ii],j[ii]) for ii in range(len(i))]

[(0, 1),
 (1, 1),
 (2, 0),
 (2, 2),
 (2, 3),
 (3, 1),
 (3, 2),
 (5, 0),
 (5, 3),
 (6, 1),
 (9, 0),
 (9, 1)]

In [24]:
idx = [1,2,3,4,5]
np_matrix[len(idx)-1,:]

array([0, 1, 3, 0, 0])

# EX. 3

In [30]:
idx = [1,2,3,4,5]
np_matrix[len(idx)-1:]

array([[1, 2, 0, 2, 2]])

In [31]:
rng = np.random.RandomState(0)
np_matrix = rng.randint(3,size = (5,5))
np_matrix

array([[0, 1, 0, 1, 1],
       [2, 0, 2, 0, 0],
       [0, 2, 1, 2, 2],
       [0, 1, 1, 1, 1],
       [0, 1, 0, 0, 1]])

In [32]:
np_matrix = np.delete(np_matrix,[1,1],0)
np_matrix

array([[0, 1, 0, 1, 1],
       [0, 2, 1, 2, 2],
       [0, 1, 1, 1, 1],
       [0, 1, 0, 0, 1]])

In [33]:
np_matrix = np.random.randint(10,size = (5,5))
np_matrix

array([[6, 6, 8, 1, 2],
       [8, 5, 3, 4, 9],
       [3, 3, 6, 0, 0],
       [3, 0, 7, 6, 8],
       [2, 3, 6, 8, 5]])

In [34]:
result = (np_matrix == 2)
result

array([[False, False, False, False,  True],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [ True, False, False, False, False]])

In [38]:
np_matrix[result] = 10
np_matrix

array([[ 6,  6,  8,  1, 10],
       [ 8,  5,  3,  4,  9],
       [ 3,  3,  6,  0,  0],
       [ 3,  0,  7,  6,  8],
       [10,  3,  6,  8,  5]])

# EX. 4

In [40]:
matrix = np.random.randint(10,size = (10,5))
matrix

array([[3, 1, 4, 7, 6],
       [3, 8, 9, 4, 2],
       [6, 0, 9, 7, 4],
       [3, 3, 5, 3, 7],
       [7, 5, 8, 9, 7],
       [8, 1, 8, 6, 6],
       [3, 6, 8, 0, 0],
       [9, 8, 8, 9, 4],
       [8, 1, 0, 2, 9],
       [7, 0, 6, 7, 7]])

In [41]:
label_vector = np.random.randint(2,size = 10)
label_vector

array([0, 1, 1, 1, 0, 0, 1, 0, 0, 1])

In [42]:
train_data = matrix[np.where(label_vector == 0)]
train_data

array([[3, 1, 4, 7, 6],
       [7, 5, 8, 9, 7],
       [8, 1, 8, 6, 6],
       [9, 8, 8, 9, 4],
       [8, 1, 0, 2, 9]])

In [43]:
test_data = matrix[np.where(label_vector == 1)]
test_data

array([[3, 8, 9, 4, 2],
       [6, 0, 9, 7, 4],
       [3, 3, 5, 3, 7],
       [3, 6, 8, 0, 0],
       [7, 0, 6, 7, 7]])